apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dotnet-test-tertr6yyt 
  janus-idp.io/tekton: dotnet-test-tertr6yyt
  backstage.io/kubernetes-id: dotnet-test-tertr6yyt
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet-test-tertr6yyt
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  