apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet-test-tertr6yyt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-test-tertr6yyt 
  name: dotnet-test-tertr6yyt
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet-test-tertr6yyt 
